"""CCCP 通用算子层。"""

from .api import (
    attention_step,
    block_scaled_gemm,
    block_scaled_gemv,
    block_scaled_grouped_gemm,
    block_scaled_grouped_gemv,
    block_scaled_grouped_rows_gemv,
    compressed_state_update,
    create_resident_projection_layer,
    create_resident_moe_layer,
    create_latent_resident_moe_layer,
    dense_grouped_gemv,
    dense_gemv,
    dense_vq_dequant_packed,
    dense_vq_dequant_fp8_packed,
    dense_vq_expand_fp8_tile,
    dense_vq_quantize_fp8_codebook,
    dense_vq_gemv_packed,
    dense_vq_mma_packed_m1,
    head_rmsnorm_rope,
    create_tensor_parallel,
    gated_activation,
    hyper_connection_post,
    hyper_connection_post_moe,
    hyper_connection_pre_norm,
    linear,
    linear_batch,
    linear_grouped_rows,
    linear_route_topk,
    ordered_recurrent_scan,
    packed_moe_topk,
    packed_moe_topk_grouped,
    projection_dequant,
    packed_moe_selected_topk,
    packed_moe_selected_rows,
    packed_moe_operator_name,
    packed_h2d_batch,
    packed_route_slots,
    paged_indexer_logits,
    persistent_topk_exact,
    sparse_paged_attention_splitkv,
    fused_compressor_cache_store,
    resident_moe_topk,
    resident_moe_forward_rows,
    residual_add3,
    residual_mix,
    route_topk,
    rmsnorm,
    vq_gemv,
    vq_gemv_packed_list,
    vq_relayout_block_major,
    vq_relayout_row_tile,
    vq_compile_u16_row_tile,
    vq_compile_q4_0,
)
from .decode_control import DecodeControl
from .attention_prefill import causal_latent_prefill
from .hidden import TPHidden, TPPartials, TPResidualBuffer, TPSharded
from .moe import FixedMoEPrelude, FixedMoEPreludeSpec
from .profiling import TPHiddenStageProfiler
from .paged_sparse import (
    IndexerFP8PagedCache,
    Model1FP8PagedCache,
    cuda_architecture_features,
)
from .config import ModelOperatorConfig
from .registry import OperatorRegistry, REGISTRY
from .sdpa import (
    native_gqa_sdpa,
    register_transformers_native_gqa_attention,
)
from .spec import OperatorCapability, OperatorRequest
from .fixed_graph import FixedAddressCudaGraph
from .tensor_parallel import (
    PackedMoEFinalizerSpec,
    ReplicatedLinearSpec,
    ReplicatedSubgroupTensorParallel,
    RoutePackedPlanSpec,
    TensorParallelAllRankCollective,
    TensorParallelDecodeLayerPlan,
    TensorParallelHyperConnectionDecodeLayerPlan,
    TensorParallelMoELayerPlan,
    TensorParallelPackedMoEFinalizer,
    TensorParallelReplicatedLinear,
    TensorParallelRoutePackedPlan,
    TensorParallelVocab,
    shard_linear_input,
    shard_linear_output,
)
from .vq_fp8 import DenseVQFP8TileMMA

__all__ = [
    "DecodeControl",
    "DenseVQFP8TileMMA",
    "ModelOperatorConfig",
    "OperatorCapability",
    "OperatorRegistry",
    "OperatorRequest",
    "IndexerFP8PagedCache",
    "Model1FP8PagedCache",
    "cuda_architecture_features",
    "FixedAddressCudaGraph",
    "REGISTRY",
    "native_gqa_sdpa",
    "register_transformers_native_gqa_attention",
    "attention_step",
    "causal_latent_prefill",
    "block_scaled_gemm",
    "block_scaled_gemv",
    "block_scaled_grouped_gemm",
    "block_scaled_grouped_gemv",
    "block_scaled_grouped_rows_gemv",
    "compressed_state_update",
    "create_resident_projection_layer",
    "create_resident_moe_layer",
    "create_latent_resident_moe_layer",
    "dense_grouped_gemv",
    "dense_gemv",
    "dense_vq_dequant_packed",
    "dense_vq_dequant_fp8_packed",
    "dense_vq_expand_fp8_tile",
    "dense_vq_quantize_fp8_codebook",
    "dense_vq_gemv_packed",
    "dense_vq_mma_packed_m1",
    "head_rmsnorm_rope",
    "create_tensor_parallel",
    "gated_activation",
    "hyper_connection_post",
    "hyper_connection_post_moe",
    "hyper_connection_pre_norm",
    "linear",
    "linear_batch",
    "linear_grouped_rows",
    "linear_route_topk",
    "ordered_recurrent_scan",
    "packed_moe_topk",
    "packed_moe_topk_grouped",
    "projection_dequant",
    "packed_moe_selected_topk",
    "packed_moe_selected_rows",
    "packed_moe_operator_name",
    "packed_h2d_batch",
    "packed_route_slots",
    "paged_indexer_logits",
    "persistent_topk_exact",
    "sparse_paged_attention_splitkv",
    "fused_compressor_cache_store",
    "resident_moe_topk",
    "resident_moe_forward_rows",
    "residual_add3",
    "residual_mix",
    "route_topk",
    "rmsnorm",
    "TPHidden",
    "TPHiddenStageProfiler",
    "TPPartials",
    "TPResidualBuffer",
    "TPSharded",
    "PackedMoEFinalizerSpec",
    "ReplicatedLinearSpec",
    "ReplicatedSubgroupTensorParallel",
    "RoutePackedPlanSpec",
    "TensorParallelAllRankCollective",
    "TensorParallelMoELayerPlan",
    "TensorParallelDecodeLayerPlan",
    "TensorParallelHyperConnectionDecodeLayerPlan",
    "TensorParallelPackedMoEFinalizer",
    "TensorParallelReplicatedLinear",
    "TensorParallelRoutePackedPlan",
    "TensorParallelVocab",
    "shard_linear_input",
    "shard_linear_output",
    "FixedMoEPrelude",
    "FixedMoEPreludeSpec",
    "vq_gemv",
    "vq_gemv_packed_list",
    "vq_relayout_block_major",
    "vq_relayout_row_tile",
    "vq_compile_u16_row_tile",
    "vq_compile_q4_0",
]
